# Generated by Django 6.0.7 on 2026-07-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='last_escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
