# Generated by Django 6.0.7 on 2026-07-30 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_alter_notificationlog_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='ack_code',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
