services:
  evolution-api:
    image: evoapicloud/evolution-api:latest
    container_name: evolution_api
    restart: always
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - "8080:8080"
    environment:
      - SERVER_URL=http://localhost:8080
      - DOCKER_ENV=true
      - AUTHENTICATION_TYPE=apikey
      - AUTHENTICATION_API_KEY=pharmacy-secret-api-key
      - INSTANCE_NAME=pharmacy-alerts
      - DATABASE_ENABLED=true
      - DATABASE_PROVIDER=postgresql
      - DATABASE_CONNECTION_URI=postgresql://neondb_owner:npg_5UXowY8HvLxl@ep-bold-mode-ayp0uckn-pooler.c-5.us-east-2.aws.neon.tech/neondb?sslmode=require&schema=evolution
      - CACHE_REDIS_ENABLED=false
      - WEBHOOK_GLOBAL_ENABLED=true
      - WEBHOOK_GLOBAL_URL=http://host.docker.internal:8000/api/whatsapp/webhook/
      - WEBHOOK_GLOBAL_WEBHOOK_BY_EVENTS=true
      - WEBHOOK_EVENTS_MESSAGES_UPSERT=true
    volumes:
      - evolution_instances:/evolution/instances

volumes:
  evolution_instances: