# Generated by Django 6.0.7 on 2026-07-28 00:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugcategory',
            name='alert_lead_time_days',
            field=models.PositiveIntegerField(default=30, help_text='Lead time must be at least 8 days so the Amber warning window (7 < days <= lead_time) is not skipped.', validators=[django.core.validators.MinValueValidator(8)]),
        ),
    ]
